### ISSUE TITLE
Bug: several packages fail to build

### ISSUE THREAD

**Issue by pandaninjas** [kreatolinux/kpkg-repo#30]
This was only tested on GitHub Actions, so take the results with a grain of salt

- [x] atk
- [x] btrfs-progs
- [x] cairo
- [ ] conmon
- [x] #36
- [x] fontconfig
- [x] foot
- [x] freetype-harfbuzz
- [ ] #35
- [x] gdk-pixbuf
- [x] glib
- [x] go
- [x] grim
- [x] iconv
- [x] isl
- [x] jp2a
- [x] libdrm
- [ ] libepoxy
- [ ] libglvnd
- [ ] libinput
- [x] libpcre
- [x] libsixel
- [x] libxkbcommon
- [ ] llvm
- [x] lvm2
- [x] mari
- [ ] mesa
- [x] nano
- [x] nasm
- [x] ncurses
- [x] nghttp2
- [ ] npth
- [x] opendoas
- [ ] #37
- [ ] openssh
- [x] openssl
- [ ] ostree
- [ ] p11-kit
- [ ] pango
- [x] pcre
- [x] perl
- [ ] pipewire
- [x] pixman
- [ ] podman
- [ ] popt
- [x] procps-ng
- [ ] python
- [ ] python-mako
- [x] readline
- [x] runit
- [x] seatd
- [x] slurp
- [x] sudo
- [ ] sway
- [ ] swaybg
- [ ] texinfo
- [x] util-linux
- [x] wayland
- [x] wayland-protocols
- [ ] wl-clipboard
- [ ] wlroots
- [x] wpa_supplicant
- [x] xkeyboard-config
- [x] xz-utils
- [x] yaml

**Comment by pandaninjas** [comment]
See: https://github.com/pandaninjas/nyaa-repo/actions/runs/4020123408

**Comment by pandaninjas** [comment]
Many of these seem to be failing due to `meson` breaking (major update?)

**Comment by eli-schwartz** [comment]
```
now building atk
sh: pip: not found
sh: meson: not found
ninja: entering directory 'build'
ninja: chdir: No such file or directory
ninja: entering directory 'build'
ninja: chdir: No such file or directory
```

Sounds like a workflow issue, your build image is a bit *too* minimal. ;) Needs to have python / pip installed.

**Comment by pandaninjas** [comment]
> ```
> now building atk
> sh: pip: not found
> sh: meson: not found
> ninja: entering directory 'build'
> ninja: chdir: No such file or directory
> ninja: entering directory 'build'
> ninja: chdir: No such file or directory
> ```
> 
> Sounds like a workflow issue, your build image is a bit _too_ minimal. ;) Needs to have python / pip installed.

It should in theory have python from meson

**Comment by pandaninjas** [comment]
Meson breaks because there's no pip

**Comment by kreatoo** [comment]
Probably cuz of pip.
Ill look onto it, thanks.

**Comment by kreatoo** [comment]
https://github.com/kreatolinux/nyaa3/actions/runs/4028463317/jobs/6925375585
Will hopefully be fixed once this builds.
