### ISSUE TITLE
Infozip binary package doesn't work, while source does

### ISSUE THREAD

**Issue by pandaninjas** [kreatolinux/kpkg-repo#74]
# Problem
Infozip binary package doesn't work, while source does
# What should've happened
Both work
# What actually happened
Only source works
# Rootfs type
Builder

**Comment by kreatoo** [comment]
What do you mean by "doesn't work"? Need more info

**Comment by pandaninjas** [comment]
the zip executable isn't found and unzip defaults to the busybox zip

**Comment by kreatoo** [comment]
Should be resolved after [CI succeeds](https://github.com/kreatolinux/kpkg-repo/actions/runs/5954244956)
